// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu0MHn4sUpaRR-NaEPFvo0ad2rHI2q24c',
    appId: '1:584426347598:android:c0b5d54b73d2a0e18df71f',
    messagingSenderId: '584426347598',
    projectId: 'aiotracker-db',
    storageBucket: 'aiotracker-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCsX3oi4cMBjT7E3zw2kV-UNZRBw2lG0Q',
    appId: '1:584426347598:ios:b1a0ed8fc90714c78df71f',
    messagingSenderId: '584426347598',
    projectId: 'aiotracker-db',
    storageBucket: 'aiotracker-db.appspot.com',
    androidClientId: '584426347598-bb8q8obo4k2i52jlkt85qjl0ut59q2es.apps.googleusercontent.com',
    iosClientId: '584426347598-cqria72bngkv0hqt8rcs8nfn19sdt9ls.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyTracker',
  );

}